/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function(knex) {
    return knex.schema
    .createTable("permission", (table) => {
    table.increments("id");
    table.string("name", 255).notNullable().comment('Название правила');
    table.string("codeName", 255).notNullable().comment('Кодовое название правила');
    table.string("tableName", 255).notNullable().comment('Таблица')
    table.timestamps(true, true, true);
    table.string("createdBy").notNullable();
    table.string("updatedBy").notNullable();
})
.then(() => {
    return knex("permission").insert([
    {
        name: 'Добавить запись в справочник bodypart',
        codeName: 'add_bodyPart',
        tableName: 'bodyPart',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике bodypart',
        codeName: 'update_bodyPart',
        tableName: 'bodyPart',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике bodypart',
        codeName: 'delete_bodyPart',
        tableName: 'bodyPart',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике bodypart',
        codeName: 'read_bodyPart',
        tableName: 'bodyPart',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник radionuclide',
        codeName: 'add_radionuclide',
        tableName: 'radionuclide',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике radionuclide',
        codeName: 'update_radionuclide',
        tableName: 'radionuclide',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике radionuclide',
        codeName: 'delete_radionuclide',
        tableName: 'radionuclide',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике radionuclide',
        codeName: 'read_radionuclide',
        tableName: 'radionuclide',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник profession',
        codeName: 'add_profession',
        tableName: 'profession',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике profession',
        codeName: 'update_profession',
        tableName: 'profession',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике profession',
        codeName: 'delete_profession',
        tableName: 'profession',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике profession',
        codeName: 'read_profession',
        tableName: 'profession',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник limitValue',
        codeName: 'add_limitValue',
        tableName: 'limitValue',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике limitValue',
        codeName: 'update_limitValue',
        tableName: 'limitValue',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике limitValue',
        codeName: 'delete_limitValue',
        tableName: 'limitValue',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике limitValue',
        codeName: 'read_limitValue',
        tableName: 'limitValue',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник roles',
        codeName: 'add_roles',
        tableName: 'roles',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике roles',
        codeName: 'update_roles',
        tableName: 'roles',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике roles',
        codeName: 'delete_roles',
        tableName: 'roles',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике roles',
        codeName: 'read_roles',
        tableName: 'roles',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник users',
        codeName: 'add_users',
        tableName: 'users',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике users',
        codeName: 'update_users',
        tableName: 'users',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике users',
        codeName: 'delete_users',
        tableName: 'users',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике users',
        codeName: 'read_users',
        tableName: 'users',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник kindIdc',
        codeName: 'add_kindIdc',
        tableName: 'kindIdc',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике kindIdc',
        codeName: 'update_kindIdc',
        tableName: 'kindIdc',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике kindIdc',
        codeName: 'delete_kindIdc',
        tableName: 'kindIdc',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике kindIdc',
        codeName: 'read_kindIdc',
        tableName: 'kindIdc',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник department',
        codeName: 'add_department',
        tableName: 'department',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике department',
        codeName: 'update_department',
        tableName: 'department',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике department',
        codeName: 'delete_department',
        tableName: 'department',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике department',
        codeName: 'read_department',
        tableName: 'department',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник FL',
        codeName: 'add_FL',
        tableName: 'FL',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике FL',
        codeName: 'update_FL',
        tableName: 'FL',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике FL',
        codeName: 'delete_FL',
        tableName: 'FL',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике FL',
        codeName: 'read_FL',
        tableName: 'FL',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник fl_ch_fio',
        codeName: 'add_fl_ch_fio',
        tableName: 'fl_ch_fio',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике fl_ch_fio',
        codeName: 'update_fl_ch_fio',
        tableName: 'fl_ch_fio',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике fl_ch_fio',
        codeName: 'delete_fl_ch_fio',
        tableName: 'fl_ch_fio',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике fl_ch_fio',
        codeName: 'read_fl_ch_fio',
        tableName: 'fl_ch_fio',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник fl_born',
        codeName: 'add_fl_born',
        tableName: 'fl_born',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике fl_born',
        codeName: 'update_fl_born',
        tableName: 'fl_born',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике fl_born',
        codeName: 'delete_fl_born',
        tableName: 'fl_born',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике fl_born',
        codeName: 'read_fl_born',
        tableName: 'fl_born',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник fl_address',
        codeName: 'add_fl_address',
        tableName: 'fl_address',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике fl_address',
        codeName: 'update_fl_address',
        tableName: 'fl_address',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике fl_address',
        codeName: 'delete_fl_address',
        tableName: 'fl_address',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике fl_address',
        codeName: 'read_fl_address',
        tableName: 'fl_address',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в справочник fl_docs',
        codeName: 'add_fl_docs',
        tableName: 'fl_docs',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в справочнике fl_docs',
        codeName: 'update_fl_docs',
        tableName: 'fl_docs',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в справочнике fl_docs',
        codeName: 'delete_fl_docs',
        tableName: 'fl_docs',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в справочнике fl_docs',
        codeName: 'read_fl_docs',
        tableName: 'fl_docs',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в таблице mainPersonalTable',
        codeName: 'add_mainPersonalTable',
        tableName: 'mainPersonalTable',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в таблице mainPersonalTable',
        codeName: 'update_mainPersonalTable',
        tableName: 'mainPersonalTable',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в таблице mainPersonalTable',
        codeName: 'delete_mainPersonalTable',
        tableName: 'mainPersonalTable',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в таблице mainPersonalTable',
        codeName: 'read_mainPersonalTable',
        tableName: 'mainPersonalTable',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в таблице docHeader',
        codeName: 'add_docHeader',
        tableName: 'docHeader',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в таблице docHeader',
        codeName: 'update_docHeader',
        tableName: 'docHeader',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в таблице docHeader',
        codeName: 'delete_docHeader',
        tableName: 'docHeader',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в таблице docHeader',
        codeName: 'read_docHeader',
        tableName: 'docHeader',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в таблице docFile',
        codeName: 'add_docFile',
        tableName: 'docFile',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в таблице docFile',
        codeName: 'update_docFile',
        tableName: 'docFile',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в таблице docFile',
        codeName: 'delete_docFile',
        tableName: 'docFile',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в таблице docFile',
        codeName: 'read_docFile',
        tableName: 'docFile',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в таблице docBpe',
        codeName: 'add_docBpe',
        tableName: 'docBpe',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в таблице docBpe',
        codeName: 'update_docBpe',
        tableName: 'docBpe',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в таблице docBpe',
        codeName: 'delete_docBpe',
        tableName: 'docBpe',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в таблице docBpe',
        codeName: 'read_docBpe',
        tableName: 'docBpe',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в таблице docHrs',
        codeName: 'add_docHrs',
        tableName: 'docHrs',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в таблице docHrs',
        codeName: 'update_docHrs',
        tableName: 'docHrs',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в таблице docHrs',
        codeName: 'delete_docHrs',
        tableName: 'docHrs',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в таблице docHrs',
        codeName: 'read_docHrs',
        tableName: 'docHrs',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в таблице docErd',
        codeName: 'add_docErd',
        tableName: 'docErd',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в таблице docErd',
        codeName: 'update_docErd',
        tableName: 'docErd',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в таблице docErd',
        codeName: 'delete_docErd',
        tableName: 'docErd',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в таблице docErd',
        codeName: 'read_docErd',
        tableName: 'docErd',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в таблице docCtc',
        codeName: 'add_docCtc',
        tableName: 'docCtc',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в таблице docCtc',
        codeName: 'update_docCtc',
        tableName: 'docCtc',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в таблице docCtc',
        codeName: 'delete_docCtc',
        tableName: 'docCtc',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в таблице docCtc',
        codeName: 'read_docCtc',
        tableName: 'docCtc',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в таблице userAssignRole',
        codeName: 'add_userAssignRole',
        tableName: 'userAssignRole',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в таблице userAssignRole',
        codeName: 'update_userAssignRole',
        tableName: 'userAssignRole',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в таблице userAssignRole',
        codeName: 'delete_userAssignRole',
        tableName: 'userAssignRole',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в таблице userAssignRole',
        codeName: 'read_userAssignRole',
        tableName: 'userAssignRole',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Добавить запись в таблице permission',
        codeName: 'add_permission',
        tableName: 'permission',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Обновить запись в таблице permission',
        codeName: 'update_permission',
        tableName: 'permission',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Удалить запись в таблице permission',
        codeName: 'delete_permission',
        tableName: 'permission',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    {
        name: 'Посмотреть запись в таблице permission',
        codeName: 'read_permission',
        tableName: 'permission',
        createdBy: 'migrations',
        updatedBy: 'migrations',
    },
    
    ])
});
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function(knex) {
    return knex.schema.dropTable("permission");
};
